# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 720add3df5a3edd9abb447293b4be80f6cffb3b5c00440de7d14c8c2ca3487f02a96c97ac9b41394a3eab2bedc6bbcf3cdfdabe1617359051ce15c4f51fccdbd

test:
  secret_key_base: 0a793f436d5975ad5b5ab65f3dc1542e756797661900829772c633f25284e744eddbc234d1ffb623f8df6d64d24f5fbb4c292ed51ce5f7ad4dadd0bdbb965886

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
